language: swift
osx_image: xcode11.3
xcode_workspace: FlickrFindr.xcworkspace
xcode_scheme: FlickrFindr
xcode_destination: platform=iOS Simulator,OS=13.3,name=iPhone 11

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8

before_install:
  - gem install bundler -v 2.0.1
  - bundle install
